PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo: <http://fr.dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdws: <http://www.wikidata.org/wiki/Special:EntityData/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
  ?URI      a                   dbo:species;
            rdfs:label          ?scientificName;
            dbo:family          ?family;
            wdws:P141           ?status;
            wdws:P225           ?commonName;
            foaf:primaryTopic   ?specie_ID.
  ?family   a                   dbo:family;
            rdfs:label          ?familyName;
            rdf:category        ?group.
  ?group    a                   rdf:category;
            rdfs:label          ?groupName;
            rdfs:range          ?type.
  ?type     a                   rdfs:range;
            rdfs:label          ?typeName;
}
FROM <file:datasetWebSemantic.csv>
WHERE {
  BIND (URI(CONCAT('http://dbpedia.org/ontology/species/', ?Scientific_name)) AS ?URI)
  BIND (xsd:string(?Scientific_name) AS ?scientificName)
  BIND (URI(CONCAT('http://dbpedia.org/ontology/family/', ?Family)) AS ?family)
  BIND (xsd:string(?Family) AS ?familyName)
  BIND (xsd:string(?Status) AS ?status)
  BIND (URI(CONCAT('http://www.w3.org/1999/02/22-rdf-syntax-ns#category/', ?Group)) AS ?group)
  BIND (xsd:string(?Group) AS ?groupName)
  BIND (xsd:string(?Common_name) AS ?commonName)
  BIND (URI(CONCAT('http://www.w3.org/2000/01/rdf-schema#range/', ?Type)) AS ?type)
  BIND (xsd:string(?Type) AS ?typeName)
  BIND (xsd:string(?Specie_ID) AS ?specie_ID)
}
